# Generated by Django 5.1.4 on 2025-06-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutrecord',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
