# Generated by Django 5.1.4 on 2025-06-28 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0002_alter_workoutrecord_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutrecord',
            name='created_at',
        ),
    ]
