# Generated by Django 5.1.4 on 2025-06-28 03:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_workout', '0003_remove_workoutrecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutrecord',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 28, 3, 6, 55, 551796, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
