# Generated by Django 5.1.4 on 2025-04-25 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_category', models.IntegerField(choices=[(0, '朝トレ'), (1, '夜トレ')])),
                ('type_category', models.IntegerField(choices=[(0, 'ストレッチ'), (1, '筋トレ'), (2, 'フォームローラー'), (3, 'マッサージ')])),
                ('body_part_category', models.IntegerField(choices=[(0, '姿勢'), (1, '全身'), (2, '脚'), (3, 'お腹'), (4, '上半身'), (5, '骨盤矯正'), (6, '顔')])),
                ('duration_time', models.CharField(max_length=5)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('youtuber_name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
