# Generated by Django 5.1.4 on 2025-04-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(0, '姿勢'), (1, '全身'), (2, '脚'), (3, 'お腹'), (4, '上半身'), (5, '骨盤矯正'), (6, '顔')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(0, '朝トレ'), (1, '夜トレ')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(0, 'ストレッチ'), (1, '筋トレ'), (2, 'フォームローラー'), (3, 'マッサージ')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='body_part_category',
        ),
        migrations.RemoveField(
            model_name='video',
            name='time_category',
        ),
        migrations.RemoveField(
            model_name='video',
            name='type_category',
        ),
        migrations.AddField(
            model_name='video',
            name='body_part_category',
            field=models.ManyToManyField(to='app_video.bodypartcategory'),
        ),
        migrations.AddField(
            model_name='video',
            name='time_category',
            field=models.ManyToManyField(to='app_video.timecategory'),
        ),
        migrations.AddField(
            model_name='video',
            name='type_category',
            field=models.ManyToManyField(to='app_video.typecategory'),
        ),
    ]
