# Generated by Django 5.1.4 on 2025-04-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0002_bodypartcategory_timecategory_typecategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='body_part_category',
        ),
        migrations.RemoveField(
            model_name='video',
            name='time_category',
        ),
        migrations.RemoveField(
            model_name='video',
            name='type_category',
        ),
        migrations.DeleteModel(
            name='BodyPartCategory',
        ),
        migrations.AddField(
            model_name='video',
            name='body_part_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='TimeCategory',
        ),
        migrations.AddField(
            model_name='video',
            name='time_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='TypeCategory',
        ),
        migrations.AddField(
            model_name='video',
            name='type_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
