# Generated by Django 5.1.4 on 2025-05-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0003_remove_video_body_part_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_template',
            field=models.BooleanField(default=False),
        ),
    ]
