# Generated by Django 5.1.4 on 2025-05-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0004_video_is_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration_seconds',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
