# Generated by Django 5.1.4 on 2025-07-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(verbose_name='身長'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(verbose_name='体重'),
        ),
    ]
