# Generated by Django 5.1.4 on 2025-07-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_height_alter_user_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.FloatField(null=True, verbose_name='身長'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.FloatField(null=True, verbose_name='体重'),
        ),
    ]
